### ISSUE TITLE
PA3

### ISSUE THREAD

**Issue by akimovatatiana** [mrol1114/rp#1]
RankCalculator не рассчитывает ранг, в логи ничего не пишется

**Comment by mrol1114** [comment]
Забыл подмержить последние изменения, была проблема с консоль лог, ошибка там падала.

**Comment by akimovatatiana** [comment]
Ранг все еще не расчитывается, и теперь, когда повторно отправляешь форму, не переходит на страницу summary и вылетает 400 ошибка. Исключение в valuator:
`2024-04-21 20:26:07 fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
2024-04-21 20:26:07       An exception was thrown while deserializing the token.
2024-04-21 20:26:07       Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
2024-04-21 20:26:07        ---> System.Security.Cryptography.CryptographicException: The key {f0019d22-fb18-4ad4-a8f6-eb079918e450} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
2024-04-21 20:26:07          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
2024-04-21 20:26:07          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
2024-04-21 20:26:07          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
2024-04-21 20:26:07          --- End of inner exception stack trace ---
2024-04-21 20:26:07          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
2024-04-21 20:26:07          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)`

**Comment by mrol1114** [comment]
По умолчанию включены csrf токены в формы, отключил их, при наличии нескольких инстансов приложения в докере вылетает такая ошибка из-за кэширования этих токенов, когда меняется инстанс ключ не меняется и происходит такая ошибка, баг плавающий зависит от того на какой инстанс приложения перекинет nginx
